% Author:        Léo Martire.
% Description:   Given some space/time specifications, formats a relevant machine-readable filename.
% Notes:         N/A.
%
% Usage:         filename = model_namer(altMin, altMax, nLayers, lat, lon, yyears, ddays, ssecs, wProjAng)

function filename = model_namer(altMin, altMax, nLayers, lat, lon, yyears, ddays, ssecs, wProjAng)
  filename = [num2str(2000+yyears), '_', ...
              num2str(ddays), '_', ...
              sprintf('%.d', ssecs), '_', ...
              sprintf('%.5f', lat), '_', ...
              sprintf('%.5f', lon), '_', ...
              num2str(altMin), '_', ...
              num2str(altMax), '_', ...
              num2str(nLayers), '_', ...
              sprintf('%.5f', wProjAng)];
end

